trainer:
  devices: 1
  accelerator: gpu
  min_epochs: 10
  max_epochs: 30
  benchmark: True
  precision: 32
experiment:
  task:
    model_name: "unet"
    model_args:
      in_channels: 15
      encoder_name: "resnet18"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 5
    learning_rate_schedule_threshold: 0.1
    loss: "rmse"
  datamodule:
    root_dir: ${program.data_dir}
    train_ratio: 0.8
    batch_size: 20
    num_workers: 4
    dataset_limit: null
    use_best_month: True
    month_items: True
    jpg_format: True
    transforms:
      - name: sentinel_band_normalize
        norm_x: False
        norm_y: True
      - name: select_bands
        bands: all
      - name: aggregate_months
        agg_fn: "mean"
